Issue34
Jonaseli/SE2020-Gruppe12 pull request #54
Opened 2020-10-27 21:26 UTC by haros-dev

1. Changed all instances of String id to UUID (including Repository class and interface, all classes and child classes.).
2. Removed some superfluous (unneeded) functions from Corporation
3. Added a constructor for User
4. Renamed some variables (e.g. ID -> Id)
5. Changed JSON id-values to correct format (UUID)
6. Changed Vue-file to reflect changes in variable names

Note: We can now look into making functions (in Repo/iRepo) to create Corp and User separately instead of creating an instance of Account.

2020-10-28 11:42 UTC, Jonaseli requested changes
Alt ser bra ut, men det ligger med en fil som heter "git" som er tom. Kan du evt. fjerne denne?

2020-10-28 13:03 UTC, 42-Broenstudentavis approved these changes

2020-10-29 09:05 UTC, Hawski approved these changes

2020-10-29 12:49 UTC, Jonaseli approved these changes

2020-10-29 12:49 UTC, merged